import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import NextAuthProvider from "./context/NextAuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
        <NextAuthProvider>
    <html lang="en">
      <body className={inter.className}> 
      <div className="w-10/12 m-auto text-center bg-white flex flex-col min-h-screen">
            <div className="grow">{children}</div>
          </div>
        </body>
    </html>
    </NextAuthProvider>
  );
}
